<a href="https://colab.research.google.com/github/cryssoga/DSWP/blob/master/Li%C3%A7%C3%A3o/CHURN_Modelo4_LogisticRegression_menoscolunas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url_train = 'https://raw.githubusercontent.com/cryssoga/DSWP/master/Li%C3%A7%C3%A3o/train.csv'
url_test = 'https://raw.githubusercontent.com/cryssoga/DSWP/master/Li%C3%A7%C3%A3o/test.csv'
url_sample_submission = 'https://raw.githubusercontent.com/cryssoga/DSWP/master/Li%C3%A7%C3%A3o/sample_submission.csv'

# Lendo/carregando os dataframes:

df_train = pd.read_csv(url_train)
df_test = pd.read_csv(url_test)
df_sample_submission = pd.read_csv(url_sample_submission)

# 'TotalCharges' de object para numeric, mas antes tratando os campos ' ':

df_train[df_train['TotalCharges']==' ']
df_train['TotalCharges'] = df_train['TotalCharges'].replace(' ', '0')
df_train['TotalCharges'] = pd.to_numeric(df_train['TotalCharges'])
df_train['TotalCharges'].replace(0, df_train['TotalCharges'].median(), inplace = True)

df_test[df_test['TotalCharges']==' ']
df_test['TotalCharges'] = df_test['TotalCharges'].replace(' ', '0')
df_test['TotalCharges'] = pd.to_numeric(df_test['TotalCharges'])
df_test['TotalCharges'].replace(0, df_test['TotalCharges'].median(), inplace = True)

In [4]:
df_train.isna().sum()

id                    0
gender                0
SeniorCitizen         0
Partner               0
Dependents          218
tenure              461
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod        99
MonthlyCharges        0
TotalCharges          0
Churn                 0
dtype: int64

In [31]:
list(df_train[df_train['Dependents'].isna()]

KeyError: ignored

In [52]:
indice = df_train[df_train['Dependents'].isna()].index

In [33]:
indice[0]

73

In [22]:
df_train['Partner'][73]

'No'

In [54]:
indice_dependents_nan = df_train[df_train['Dependents'].isna()].index
for i in indice_dependents_nan:
    if df_train['Partner'][i]=='Yes':
        df_train['Dependents'][i] = 'Yes'
    else:
        df_train['Dependents'][i] = 'No'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [55]:
indice_dependents_nan = df_test[df_test['Dependents'].isna()].index
for i in indice_dependents_nan:
    if df_test['Partner'][i]=='Yes':
        df_test['Dependents'][i] = 'Yes'
    else:
        df_test['Dependents'][i] = 'No'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
df_train.iloc[73]

id                                  139
gender                             Male
SeniorCitizen                         0
Partner                              No
Dependents                           No
tenure                               57
PhoneService                        Yes
MultipleLines                        No
InternetService                      No
OnlineSecurity      No internet service
OnlineBackup        No internet service
DeviceProtection    No internet service
TechSupport         No internet service
StreamingTV         No internet service
StreamingMovies     No internet service
Contract                       Two year
PaperlessBilling                    Yes
PaymentMethod              Mailed check
MonthlyCharges                     19.6
TotalCharges                    1170.55
Churn                                 0
Name: 73, dtype: object

In [ ]:
# Tratando os missing values nas variáveis 'PaymentMethod' (mais frequente), 'Dependents' (mais frequente) e 'tenure' (mediana)

df_train['PaymentMethod'].fillna('Eletronic check', inplace=True)
#df_train['Dependents'].fillna('No',inplace = True)
df_train['tenure'].fillna(df_train['tenure'].median(), inplace=True)

df_test['PaymentMethod'].fillna('Eletronic check',inplace = True)
#df_test['Dependents'].fillna('No', inplace=True)
df_test['tenure'].fillna(df_test['tenure'].median(),inplace = True)

KeyError: ignored

In [ ]:
df_train[df_train['Churn']==0].head(20)

      id  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0   4030  Female              0  ...          45.05      2560.10      0
1   6731    Male              0  ...          19.65       332.65      0
2   6479  Female              0  ...         110.80      6640.70      0
5   6368    Male              0  ...          48.40      3442.80      0
6   5830    Male              0  ...          59.95      1848.80      0
7   4476  Female              0  ...          19.55        61.05      0
8   1508    Male              0  ...          19.65      1008.70      0
9   2921  Female              0  ...          85.10      6155.40      0
10  3145    Male              0  ...          18.95       110.15      0
11   333    Male              0  ...          94.90      4422.95      0
12  2140  Female              0  ...          66.85       458.10      0
14  3379    Male              0  ...          84.45      6033.10      0
15  3163    Male              0  ...          69.60      1394.55      0
16  6471    Male              0  ...          43.45       345.50      0
17  2350    Male              0  ...          90.45      6565.85      0
19   305    Male              0  ...          81.85      3141.70      0
20  6458    Male              0  ...          44.45       792.15      0
21  1124    Male              0  ...          61.60      1611.00      0
22   670  Female              0  ...          57.80      4039.30      0
23   878  Female              0  ...          60.15      3077.00      0

[20 rows x 21 columns]

In [ ]:
df_train[df_train['Churn']==1].head(20)

      id  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
3   6861  Female              0  ...         101.90      3545.35      1
4   3266    Male              0  ...          70.75      1974.80      1
13  3427    Male              0  ...          69.80        69.80      1
18  3756    Male              0  ...          76.05       318.90      1
31  4982    Male              0  ...          50.75       712.75      1
33  3008  Female              1  ...          74.40      2276.95      1
34   956    Male              0  ...          44.70        44.70      1
38  2295    Male              0  ...         106.70      1253.90      1
40   979    Male              1  ...         103.75      6383.35      1
41   192    Male              0  ...          91.00       531.00      1
45  3331    Male              1  ...          97.80      4913.30      1
52  2020    Male              0  ...         104.10      7040.85      1
57  5644    Male              0  ...          75.90        75.90      1
58  6152  Female              0  ...          71.00       672.55      1
65  4811  Female              1  ...          89.85      1424.95      1
66  3122  Female              1  ...          59.40      1023.90      1
68   105    Male              0  ...         110.00      7611.85      1
82  1988  Female              0  ...          89.15      2257.75      1
88  1891  Female              0  ...          21.00        21.00      1
93  4238    Male              0  ...          70.05       346.40      1

[20 rows x 21 columns]

In [ ]:
df_teste_completo = df_test.copy()

In [ ]:
df_teste_completo['Churn'] = df_sample_submission['Churn']

In [ ]:
def internet_service_reflexo(df):
  #df['IS_reflexo']= 0
  col_reflexo = ['OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies']
  linha = 0
  while linha < df.shape[0]:
    qtde=0
    if df['InternetService'][linha]=='No':
      qtde = 6
    else:
      for i in col_reflexo:
        if df[i] == 'Yes':
          qtde = qtde + 1
    df['IS_reflexo'][linha] = qtde

In [ ]:
internet_service_reflexo(df_teste_completo)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

KeyboardInterrupt: ignored

In [ ]:
df_teste_completo[df_teste_completo['Churn']==1].head(20)

      id  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1   1733    Male              1  ...          99.00      5969.30      1
3   6554  Female              0  ...          61.45      3751.15      1
9   5461    Male              0  ...          20.05       679.00      1
17  4626  Female              1  ...          74.05       600.15      1
20  5297  Female              0  ...          41.10      2258.25      1
21  3633  Female              0  ...          79.65      1928.70      1
23  3793  Female              1  ...          91.25      2351.80      1
24  4090  Female              0  ...          74.75       706.60      1
25  6770    Male              0  ...          19.85       916.00      1
26  3718    Male              0  ...          48.95      1323.70      1
27   786  Female              1  ...         110.00      4874.80      1
29  1809  Female              0  ...          79.15      1676.95      1
32  2790  Female              0  ...          88.95      2072.75      1
35  6668  Female              0  ...          79.55       723.40      1
37  4091  Female              0  ...          49.90        49.90      1
38  4511  Female              0  ...          68.15      2656.30      1
41  2943    Male              0  ...          19.95       907.05      1
46  1744    Male              0  ...          24.85      1583.50      1
48  3337  Female              0  ...          20.30      1079.05      1
50  6420    Male              1  ...          84.90      5785.65      1

[20 rows x 21 columns]

In [ ]:
# Dividindo df_train em df_X_train e df_y_train:
X_train = df_train.drop('Churn',axis=1)
X_test = df_test.copy()

y_train = df_train['Churn']
y_test = df_sample_submission['Churn']

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
    # 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
    # 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
    # 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
    # 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'

X_treinamento['gender_le'] = le.fit_transform(X_treinamento['gender'])
X_treinamento['SeniorCitizen_le'] = le.fit_transform(X_treinamento['SeniorCitizen'])
X_treinamento['Partner_le'] = le.fit_transform(X_treinamento['Partner'])
X_treinamento['Dependents_le'] = le.fit_transform(X_treinamento['Dependents'])
X_treinamento['PhoneService_le'] = le.fit_transform(X_treinamento['PhoneService'])
X_treinamento['MultipleLines_le'] = le.fit_transform(X_treinamento['MultipleLines'])
X_treinamento['InternetService_le'] = le.fit_transform(X_treinamento['InternetService'])
X_treinamento['OnlineSecurity_le'] = le.fit_transform(X_treinamento['OnlineSecurity'])
X_treinamento['OnlineBackup_le'] = le.fit_transform(X_treinamento['OnlineBackup'])
X_treinamento['DeviceProtection_le'] = le.fit_transform(X_treinamento['DeviceProtection'])
X_treinamento['TechSupport_le'] = le.fit_transform(X_treinamento['TechSupport'])
X_treinamento['StreamingTV_le'] = le.fit_transform(X_treinamento['StreamingTV'])
X_treinamento['StreamingMovies_le'] = le.fit_transform(X_treinamento['StreamingMovies'])
X_treinamento['Contract_le'] = le.fit_transform(X_treinamento['Contract'])
X_treinamento['PaperlessBilling_le'] = le.fit_transform(X_treinamento['PaperlessBilling'])
X_treinamento['PaymentMethod_le'] = le.fit_transform(X_treinamento['PaymentMethod'])

X_teste['gender_le'] = le.fit_transform(X_teste['gender'])
X_teste['SeniorCitizen_le'] = le.fit_transform(X_teste['SeniorCitizen'])
X_teste['Partner_le'] = le.fit_transform(X_teste['Partner'])
X_teste['Dependents_le'] = le.fit_transform(X_teste['Dependents'])
X_teste['PhoneService_le'] = le.fit_transform(X_teste['PhoneService'])
X_teste['MultipleLines_le'] = le.fit_transform(X_teste['MultipleLines'])
X_teste['InternetService_le'] = le.fit_transform(X_teste['InternetService'])
X_teste['OnlineSecurity_le'] = le.fit_transform(X_teste['OnlineSecurity'])
X_teste['OnlineBackup_le'] = le.fit_transform(X_teste['OnlineBackup'])
X_teste['DeviceProtection_le'] = le.fit_transform(X_teste['DeviceProtection'])
X_teste['TechSupport_le'] = le.fit_transform(X_teste['TechSupport'])
X_teste['StreamingTV_le'] = le.fit_transform(X_teste['StreamingTV'])
X_teste['StreamingMovies_le'] = le.fit_transform(X_teste['StreamingMovies'])
X_teste['Contract_le'] = le.fit_transform(X_teste['Contract'])
X_teste['PaperlessBilling_le'] = le.fit_transform(X_teste['PaperlessBilling'])
X_teste['PaymentMethod_le'] = le.fit_transform(X_teste['PaymentMethod'])

X_train = X_treinamento.copy()
X_test = X_teste.copy()

X_treinamento = X_treinamento.drop(['id','gender', 'SeniorCitizen', 'Partner', 'Dependents',
                                 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
                                 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
                                 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],axis=1)

X_teste = X_teste.drop(['id','gender', 'SeniorCitizen', 'Partner', 'Dependents',
                                 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
                                 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
                                 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],axis=1)
l_colunas = X_treinamento.columns

X_train = X_treinamento.copy()
X_test = X_teste.copy()

In [ ]:
X_treinamento.shape

(5634, 19)

In [ ]:
# Definindo variáveis globais:
i_CV = 10     # número de Cross-Validations (CV)
i_Seed = 20111974

from sklearn.model_selection import cross_val_score     # para CV (Cross-Validation)
from sklearn.model_selection import GridSearchCV        # para GridSearchCV (otimizar os parâmetros dos modelos preditivos)
from time import time                                   # requerida na função gridsearchcv
from sklearn.ensemble import RandomForestClassifier     # para o RandomForestClassifier
from sklearn.metrics import confusion_matrix            # para plotar a confusion matrix
import seaborn as sns

# Feature selection:
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
# https://www.kaggle.com/vinicius150987/logistic-regression-rfe
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train2 = pd.DataFrame(sc_X.fit_transform(X_train))
X_test2 = pd.DataFrame(sc_X.transform(X_test))
X_train2.columns = X_train.columns.values
X_test2.columns = X_test.columns.values
X_train2.index = X_train.index.values
X_test2.index = X_test.index.values
X_train = X_train2
X_test = X_test2

In [ ]:
#Model Building (Logistic Regression)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, penalty='l2')
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score, confusion_matrix
acc = accuracy_score(y_test,y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test,y_pred)
results = pd.DataFrame([['Logistic Regression (Lasso)', acc,prec,rec,f1]],columns=['Model', 'Accuracy', 'Precision', 'Recall','F1 Score'])
results

                         Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression (Lasso)  0.507452   0.470405  0.223704  0.303213

In [ ]:
#Applying K-folds validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator= classifier, X=X_train, y=y_train, cv=10)
accuracies.mean()
accuracies.std()
print('Logistic Regression (Lasso) Accuracy: %0.3f (+/- %0.3f)' % (accuracies.mean(), accuracies.std() * 2))

Logistic Regression (Lasso) Accuracy: 0.802 (+/- 0.047)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score, confusion_matrix
acc = accuracy_score(y_test,y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test,y_pred)
results = pd.DataFrame([['Logistic Regression (Lasso)', acc,prec,rec,f1]],columns=['Model', 'Accuracy', 'Precision', 'Recall','F1 Score'])
results

                         Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression (Lasso)  0.507452   0.470405  0.223704  0.303213

In [ ]:
#Feature selection 
#Recursive feature elimination
from sklearn.feature_selection import RFE

#Select best feature 
rfe = RFE(classifier, n_features_to_select= None)
rfe = rfe.fit(X_train, y_train)

#Summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)
X_train.columns[rfe.support_]

[ True  True False False False False False  True False  True  True  True
 False  True False False  True  True False]
[ 1  1  6 10  2  5  3  1  7  1  1  1  4  1  9 11  1  1  8]

Index(['tenure', 'MonthlyCharges', 'PhoneService_le', 'InternetService_le',
       'OnlineSecurity_le', 'OnlineBackup_le', 'TechSupport_le', 'Contract_le',
       'PaperlessBilling_le'],
      dtype='object')

In [ ]:
# Fitting Model to the Training Set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, penalty= 'l2')
classifier.fit(X_train[X_train.columns[rfe.support_]], y_train)

# Predicting Test Set
y_pred = classifier.predict(X_test[X_train.columns[rfe.support_]])
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

model_results = pd.DataFrame([['Logistic Regression RFE (Lasso)', acc, prec, rec, f1]],
               columns = ['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])

results = results.append(model_results, ignore_index = True)
results

                             Model  Accuracy  Precision    Recall  F1 Score
0      Logistic Regression (Lasso)  0.507452   0.470405  0.223704  0.303213
1  Logistic Regression RFE (Lasso)  0.501774   0.457944  0.217778  0.295181

In [ ]:
df_y_pred = pd.DataFrame(y_pred)
df_y_pred.value_counts()

0    1088
1     321
dtype: int64

In [ ]:
# Função para Cross-Validation:

def funcao_cross_val_score(modelo, X_treinamento, y_treinamento, CV):
    
    #versão com cross_val_score:
    a_scores_CV = cross_val_score(modelo, X_treinamento, y_treinamento, cv = CV)
    print(f'Média das Acurácias calculadas pelo CV....: {100*round(a_scores_CV.mean(),4)}')
    print(f'std médio das Acurácias calculadas pelo CV: {100*round(a_scores_CV.std(),4)}')
    return a_scores_CV  # é um array com os scores a cada iteração do CV

In [ ]:
# Função para Confusion Matrix:

def mostra_confusion_matrix(cf, 
                            group_names = None, 
                            categories = 'auto', 
                            count = True, 
                            percent = True, 
                            cbar = True, 
                            xyticks = False, 
                            xyplotlabels = True, 
                            sum_stats = True, 
                            figsize = (8, 8), 
                            cmap = 'Blues'):
    '''
    This function will make a pretty plot of an sklearn Confusion Matrix cm using a Seaborn heatmap visualization.
    Arguments
    ---------
    cf:            confusion matrix to be passed in
    group_names:   List of strings that represent the labels row by row to be shown in each square.
    categories:    List of strings containing the categories to be displayed on the x,y axis. Default is 'auto'
    count:         If True, show the raw number in the confusion matrix. Default is True.
    normalize:     If True, show the proportions for each category. Default is True.
    cbar:          If True, show the color bar. The cbar values are based off the values in the confusion matrix.
                   Default is True.
    xyticks:       If True, show x and y ticks. Default is True.
    xyplotlabels:  If True, show 'True Label' and 'Predicted Label' on the figure. Default is True.
    sum_stats:     If True, display summary statistics below the figure. Default is True.
    figsize:       Tuple representing the figure size. Default will be the matplotlib rcParams value.
    cmap:          Colormap of the values displayed from matplotlib.pyplot.cm. Default is 'Blues'
                   See http://matplotlib.org/examples/color/colormaps_reference.html
    '''

    # CODE TO GENERATE TEXT INSIDE EACH SQUARE
    blanks = ['' for i in range(cf.size)]

    if group_names and len(group_names)==cf.size:
        group_labels = ["{}\n".format(value) for value in group_names]
    else:
        group_labels = blanks

    if count:
        group_counts = ["{0:0.0f}\n".format(value) for value in cf.flatten()]
    else:
        group_counts = blanks

    if percent:
        group_percentages = ["{0:.2%}".format(value) for value in cf.flatten()/np.sum(cf)]
    else:
        group_percentages = blanks

    box_labels = [f"{v1}{v2}{v3}".strip() for v1, v2, v3 in zip(group_labels,group_counts,group_percentages)]
    box_labels = np.asarray(box_labels).reshape(cf.shape[0],cf.shape[1])

    # CODE TO GENERATE SUMMARY STATISTICS & TEXT FOR SUMMARY STATS
    if sum_stats:
        #Accuracy is sum of diagonal divided by total observations
        accuracy  = np.trace(cf) / float(np.sum(cf))

        #if it is a binary confusion matrix, show some more stats
        if len(cf)==2:
            #Metrics for Binary Confusion Matrices
            precision = cf[1,1] / sum(cf[:,1])
            recall    = cf[1,1] / sum(cf[1,:])
            f1_score  = 2*precision*recall / (precision + recall)
            stats_text = "\n\nAccuracy={:0.3f}\nPrecision={:0.3f}\nRecall={:0.3f}\nF1 Score={:0.3f}".format(accuracy,precision,recall,f1_score)
        else:
            stats_text = "\n\nAccuracy={:0.3f}".format(accuracy)
    else:
        stats_text = ""

    # SET FIGURE PARAMETERS ACCORDING TO OTHER ARGUMENTS
    if figsize==None:
        #Get default figure size if not set
        figsize = plt.rcParams.get('figure.figsize')

    if xyticks==False:
        #Do not show categories if xyticks is False
        categories=False

    # MAKE THE HEATMAP VISUALIZATION
    plt.figure(figsize=figsize)
    sns.heatmap(cf,annot=box_labels,fmt="",cmap=cmap,cbar=cbar,xticklabels=categories,yticklabels=categories)

    if xyplotlabels:
        plt.ylabel('True label')
        plt.xlabel('Predicted label' + stats_text)
    else:
        plt.xlabel(stats_text)

In [ ]:
# função para GridSearchCV:

def GridSearchOptimizer(modelo, ml_Opt, d_Parametros, X_treinamento, y_treinamento, X_teste, y_teste, i_CV, l_colunas):
    ml_GridSearchCV = GridSearchCV(modelo, d_Parametros, cv = i_CV, n_jobs = -1, verbose= 10, scoring = 'accuracy')
    start = time()
    ml_GridSearchCV.fit(X_treinamento, y_treinamento)
    tempo_elapsed = time()-start
    #print(f"\nGridSearchCV levou {tempo_elapsed:.2f} segundos.")

    # Parâmetros que otimizam a classificação:
    print(f'\nParametros otimizados: {ml_GridSearchCV.best_params_}')
    
    if ml_Opt == 'ml_DT2':
        print(f'\nDecisionTreeClassifier *********************************************************************************************************')
        ml_Opt = DecisionTreeClassifier(criterion= ml_GridSearchCV.best_params_['criterion'], 
                                        max_depth= ml_GridSearchCV.best_params_['max_depth'],
                                        max_leaf_nodes= ml_GridSearchCV.best_params_['max_leaf_nodes'],
                                        min_samples_split= ml_GridSearchCV.best_params_['min_samples_leaf'],
                                        min_samples_leaf= ml_GridSearchCV.best_params_['min_samples_split'], 
                                        random_state= i_Seed)
        
    elif ml_Opt == 'ml_RF2':
        print(f'\nRandomForestClassifier *********************************************************************************************************')
        ml_Opt = RandomForestClassifier(bootstrap= ml_GridSearchCV.best_params_['bootstrap'], 
                                        max_depth= ml_GridSearchCV.best_params_['max_depth'],
                                        max_features= ml_GridSearchCV.best_params_['max_features'],
                                        min_samples_leaf= ml_GridSearchCV.best_params_['min_samples_leaf'],
                                        min_samples_split= ml_GridSearchCV.best_params_['min_samples_split'],
                                        n_estimators= ml_GridSearchCV.best_params_['n_estimators'],
                                        random_state= i_Seed)
        
    elif ml_Opt == 'ml_AB2':
        print(f'\nAdaBoostClassifier *********************************************************************************************************')
        ml_Opt = AdaBoostClassifier(algorithm='SAMME.R', 
                                    base_estimator=RandomForestClassifier(bootstrap = False, 
                                                                          max_depth = 10, 
                                                                          max_features = 'auto', 
                                                                          min_samples_leaf = 1, 
                                                                          min_samples_split = 2, 
                                                                          n_estimators = 400), 
                                    learning_rate = ml_GridSearchCV.best_params_['learning_rate'], 
                                    n_estimators = ml_GridSearchCV.best_params_['n_estimators'], 
                                    random_state = i_Seed)
        
    elif ml_Opt == 'ml_GB2':
        print(f'\nGradientBoostingClassifier *********************************************************************************************************')
        ml_Opt = GradientBoostingClassifier(learning_rate = ml_GridSearchCV.best_params_['learning_rate'], 
                                            n_estimators = ml_GridSearchCV.best_params_['n_estimators'], 
                                            max_depth = ml_GridSearchCV.best_params_['max_depth'], 
                                            min_samples_split = ml_GridSearchCV.best_params_['min_samples_split'], 
                                            min_samples_leaf = ml_GridSearchCV.best_params_['min_samples_leaf'], 
                                            max_features = ml_GridSearchCV.best_params_['max_features'])
        
    elif ml_Opt == 'ml_XGB2':
        print(f'\nXGBoostingClassifier *********************************************************************************************************')
        ml_Opt = XGBoostingClassifier(learning_rate= ml_GridSearchCV.best_params_['learning_rate'], 
                                      max_depth= ml_GridSearchCV.best_params_['max_depth'], 
                                      colsample_bytree= ml_GridSearchCV.best_params_['colsample_bytree'], 
                                      subsample= ml_GridSearchCV.best_params_['subsample'], 
                                      gamma= ml_GridSearchCV.best_params_['gamma'], 
                                      min_child_weight= ml_GridSearchCV.best_params_['min_child_weight'])
        
    # Treina novamente usando os parametros otimizados...
    ml_Opt.fit(X_treinamento, y_treinamento)

    # Cross-Validation com 10 folds
    print(f'\n********* CROSS-VALIDATION ***********')
    a_scores_CV = funcao_cross_val_score(ml_Opt, X_treinamento, y_treinamento, i_CV)

    # Faz predições com os parametros otimizados...
    y_pred = ml_Opt.predict(X_teste)
  
    # Importância das COLUNAS
    print(f'\n********* IMPORTÂNCIA DAS COLUNAS ***********')
    df_importancia_variaveis = pd.DataFrame(zip(l_colunas, ml_Opt.feature_importances_), columns= ['coluna', 'importancia'])
    df_importancia_variaveis = df_importancia_variaveis.sort_values(by= ['importancia'], ascending=False)
    print(df_importancia_variaveis)

    # Matriz de Confusão
    print(f'\n********* CONFUSION MATRIX - PARAMETER TUNNING ***********')
    cf_matrix = confusion_matrix(y_teste, y_pred)
    cf_labels = ['True_Negative', 'False_Positive', 'False_Negative', 'True_Positive']
    cf_categories = ['Zero', 'One']
    mostra_confusion_matrix(cf_matrix, group_names = cf_labels, categories = cf_categories)

    return ml_Opt, ml_GridSearchCV.best_params_

In [ ]:
# Função para Decision Tree:

from sklearn.tree import DecisionTreeClassifier # Library para Decision Tree (Classificação)

ml_DT = DecisionTreeClassifier(criterion = 'gini', 
                               splitter = 'best', 
                               max_depth = None, 
                               min_samples_split = 2, 
                               min_samples_leaf = 1, 
                               min_weight_fraction_leaf = 0.0, 
                               max_features = None, 
                               random_state = i_Seed, 
                               max_leaf_nodes = None, 
                               min_impurity_decrease = 0.0, 
                               min_impurity_split = None, 
                               class_weight = None, 
                               presort = False)

## MODELO 3: RANDOM FOREST, CV e GridSearchRF (X_treinamento, X_teste)

In [ ]:
# RandomForestClassifier

# Instancia...
ml_RF= RandomForestClassifier(n_estimators=200, min_samples_split= 2, max_features="auto",random_state = i_Seed)

# Treina...
ml_RF.fit(X_treinamento, y_treinamento)

a_scores_CV = funcao_cross_val_score(ml_RF, X_treinamento, y_treinamento, i_CV)

# Faz predições...
y_pred = ml_RF.predict(X_teste)

# Dicionário de parâmetros para o parameter tunning.
d_hiperparametros_RF= {'bootstrap': [True, False],
                  'max_depth': [10,None],#[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
                  'max_features': ['auto', 'sqrt'],
                  'min_samples_leaf': [1, 2, 4],
                  'min_samples_split': [2,5], #[2, 5, 10],
                  'n_estimators': [200,400]}#[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

ml_RF2, best_params = GridSearchOptimizer(ml_RF, 'ml_RF2', d_hiperparametros_RF, X_treinamento, y_treinamento, X_teste, y_teste, i_CV, l_colunas)

Média das Acurácias calculadas pelo CV....: 79.86
std médio das Acurácias calculadas pelo CV: 1.97
Fitting 10 folds for each of 96 candidates, totalling 960 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    4.7s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    9.5s
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:   15.9s
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:   27.0s
[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:   31.8s
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   45.9s
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   53.8s
[Parallel(n_jobs=-1)]: Done  57 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  81 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done  94 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-1)]: Done 109 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 124 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 141 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  3.1min
[Parallel(n_jobs=-1)]: Done 177 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-1)]: Done 217 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-1)]: Done 238 tasks      | elapsed:  4.7min
[Parallel(n_jobs=-1)]: Done 261 tasks      | elapsed:  5.2min
[Parallel(n_jobs=-1)]: Done 284 tasks      | elapsed:  5.7min
[Parallel(n_jobs=-1)]: Done 309 tasks      | elapsed:  6.2min
[Parallel(n_jobs=-1)]: Done 334 tasks      | elapsed:  6.8min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed:  7.4min
[Parallel(n_jobs=-1)]: Done 388 tasks      | elapsed:  7.9min
[Parallel(n_jobs=-1)]: Done 417 tasks      | elapsed:  8.7min

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
#y_pred = ml_RF.predict(X_teste)

#y_teste_submit = ml_RF.predict(df_teste_submit)
df_submit = pd.DataFrame(zip(df_test['id'],y_pred), columns = ['id','Churn'])
df_submit.to_csv('submit.csv',index = False)

In [ ]:
df_submit

        id  Churn
0     5027      0
1     1733      0
2     5384      0
3     6554      0
4      364      0
...    ...    ...
1404  4897      0
1405  6940      0
1406   804      0
1407  1143      1
1408  5773      0

[1409 rows x 2 columns]